# Generated by Django 2.0.6 on 2018-06-12 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pledge', '0002_user_pledges_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Pledges',
            new_name='UserPledges',
        ),
    ]
