# Generated by Django 2.0.6 on 2018-06-13 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0003_auto_20180612_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpledges',
            name='datetime_taken',
        ),
        migrations.AddField(
            model_name='userpledges',
            name='taken_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Datetime at which user took the pledge', verbose_name='taken on'),
            preserve_default=False,
        ),
    ]
